### ISSUE TITLE
한글시계 뒷 이야기 링크 깨짐

### ISSUE THREAD

**Issue by sebuls** [suapapa/HangulClock#2]
한글시계 뒷 이야기 클릭하면
사이트에 연결할 수 없음
나옵니다.

**Comment by suapapa** [comment]
아이고. 여긴 또 왜... 수정하겠습니다.

2017. 12. 13. 오후 3:22에 "세벌" <notifications@github.com>님이 작성:

**Comment by suapapa** [comment]
수정해 두었습니다.
